namespace ProjectManagementApp
{
    [default_interface]
    runtimeclass ProyectosPage : Microsoft.UI.Xaml.Controls.Page
    {
        ProyectosPage();
        void SetProjectId(Int32 projectId);
    }
}